version: "3.5"
services:
  wordpress:
    image: wordpress:5.2.2-php7.1-apache
    hostname: wordpress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/docker/wordpress/data:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: hatlonely
      WORDPRESS_DB_PASSWORD: keaiduo1
      WORDPRESS_DB_NAME: wordpress
    networks:
      - online
networks:
  online:
    external: true
    name: online
